apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: go-example
spec:
  ports:
    - port: 4445
      targetPort: 4444
      protocol: TCP
  type: LoadBalancer
  selector:
    app: backend
